version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
      #    volumes: 
      #      - ./db/scripts/up.sql:/docker-entrypoint-initdb.d/up.sql
        #      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rocketdb
    ports:
      - '5432:5432'
volumes:
  data:
